name: auto-merge

on:
  push:
    branches: [ master, dev ]

env:
  MERGE/refs/heads/master: refs/heads/dev
  MERGE/refs/heads/dev: refs/heads/future

jobs:
  merge:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ env[format('MERGE/{0}', github.ref)] }}
        fetch-depth: 0
    - name: Merge
      run: |
        git fetch origin ${{ github.ref }}
        git merge FETCH_HEAD
    - name: Push
      run: |
        git push origin HEAD:${{ env[format('MERGE/{0}', github.ref)] }}

